version: '3.1'

services:
  app:
      build: .
      #image: docker_stack_app:latest
      restart: on-failure
      ports:
        - "8000:8000"
      depends_on:
        - "db"
      volumes:
        - .:/usr/src/app
        - static_volume:/usr/src/app/staticfiles
      env_file: .env.app
      networks:
          - recipeapi
          - database
  db:
    image: postgres
    restart: always
    env_file: .env.db
    ports:
        - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
        - database

volumes:
  static_volume:
  pgdata:
networks:
    recipeapi:
    database:
