version: '3.1'

services:

  app:
      build: .
      ports:
        - "8000:8000"
      depends_on:
        - "db"
      volumes:
        - .:/usr/src/app
        - static_volume:/usr/src/app/staticfiles
      env_file: .env.app
  db:
    image: postgres
    restart: always
    env_file: .env.db
    ports:
        - "5432:5432"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 1337:80
    depends_on:
      - app
volumes:
  static_volume:
  media_volume:
