# Generated by Django 2.1.7 on 2019-04-24 02:31

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_url', models.URLField(blank=True, default='', max_length=500, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directions_json', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('recipe_url', models.URLField(blank=True, default='', max_length=500, unique=True)),
                ('prep_time', models.CharField(max_length=10)),
                ('cook_time', models.CharField(max_length=10)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.Chef')),
                ('ingredient', models.ManyToManyField(to='recipes_app.Ingredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='directions',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='chef',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='tags',
        ),
        migrations.AlterField(
            model_name='taggedfood',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.Recipe'),
        ),
        migrations.DeleteModel(
            name='Chefs',
        ),
        migrations.DeleteModel(
            name='Directions',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='recipes_app.TaggedFood', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='direction',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.Recipe'),
        ),
    ]
