# Generated by Django 2.1.7 on 2019-05-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_auto_20190424_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='chef_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
