# Generated by Django 2.1.7 on 2019-05-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0004_auto_20190501_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='direction_text',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
